apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaimName }}
  labels:
    {{- include "b2bglobal.labels" . | nindent 4 }}
spec:
{{ toYaml .Values.persistentVolumeClaim | indent 2 }}