apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "b2bglobal.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
data:
  ADMIN_PASSWORD: bWFuYWdl
  DB_IS_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQK
  DB_IS_USER: c2EK
  DB_MWS_PASSWORD: TXlDMG05bCZ4UEBzc3cwcmQK
  DB_MWS_USER: c2EK
  DEFAULT_KEYSTORE_KEYALIAS_PASSWORD: bWFuYWdlCg==
  DEFAULT_TRUSTSTORE_KS_PASSWORD: bWFuYWdlCg==
  MWS_ADMIN_PASSWORD: bWFuYWdl
  MWS_PASSWORD: bWFuYWdl
  SAP_B2B_WMS_PASSWORD: c2Fwc2FwMTI=