apiVersion: v1
kind: Service
metadata:
  name: {{ include "terracotta-bigmemorymax.fullname" . }}-h
  labels:
    {{- include "terracotta-bigmemorymax.labels" . | nindent 8 }}
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    {{- include "terracotta-bigmemorymax.selectorLabels" . | nindent 4 }}
  ports:
{{ toYaml .Values.headlessPortDef | indent 4 }}  
  clusterIP: None