apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terracotta-bigmemorymax.fullname" . }}
  labels:
    app: {{ include "terracotta-bigmemorymax.fullname" . }}
data:
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "application/tc-config.xml" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "licenses/terracotta-license.key" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}