apiVersion: v1
kind: Service
metadata:
  name: {{ include "terracotta-bigmemorymax.fullname" . }}-h
  labels:
    app: {{ include "terracotta-bigmemorymax.fullname" . }}
  annotations:
    prometheus.io/scrape: 'true'    
    prometheus.io/port: '5555'
spec:
  selector:
    app: {{ include "terracotta-bigmemorymax.fullname" . }}
    component: caching
  ports:
{{ toYaml .Values.headlessPortDef | indent 4 }}  
  clusterIP: None