apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ include "um-runtime.fullname" . }}
  labels:
    {{- include "um-runtime.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "um-runtime.selectorLabels" . | nindent 6 }}
  {{- if not .Values.podConfig.autoScaling.enabled }}
  replicas: {{ .Values.podConfig.replicas }}
  {{- end }}
  {{- with .Values.podConfig.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "um-runtime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.podConfig.affinity }}   
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      {{- with .Values.podConfig.tolerations }}                           
      tolerations:
        {{- toYaml . | nindent 8 }}    
      {{- end }} 
      securityContext:
        {{- toYaml .Values.podConfig.podSecurityContext | nindent 8 }} 
      serviceAccountName: {{ .Values.podConfig.serviceAccountName }}
      containers:          
        - name: {{ include "um-runtime.fullname" . }}-primary-container
          image: "{{ .Values.podConfig.primaryContainer.image.repository }}:{{ .Values.podConfig.primaryContainer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.podConfig.primaryContainer.image.pullPolicy }}
          {{- with .Values.podConfig.primaryContainer.lifecycle }} 
          lifecycle:
            {{- toYaml . | nindent 12 }}  
          {{- end }}
        # Resources required for the MSR to function. CPUs and Memory configurations.
          resources:
            {{- toYaml .Values.podConfig.primaryContainer.resources | nindent 12 }} 
          {{- with .Values.podConfig.primaryContainer.env }} 
          env:
            {{- toYaml . | nindent 12 }} 
          {{- end }}
          ports:
            {{- toYaml .Values.podConfig.primaryContainer.ports | nindent 12 }} 
          {{- with .Values.podConfig.primaryContainer.livenessProbe }}
          livenessProbe:           
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podConfig.primaryContainer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.podConfig.primaryContainer.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: {{ .Values.podConfig.primaryContainer.umLicensePath }}
              subPath: {{ .Values.podConfig.primaryContainer.umLicenseFileName }}
              name: application-config 
            - name: um-data-directory   
              mountPath: {{ .Values.podConfig.primaryContainer.dataDirPath }}               
      imagePullSecrets:
        - name: {{ .Values.podConfig.imagePullSecrets }}              
      volumes:
      - name: application-config
        configMap:
          name: {{ include "um-runtime.fullname" . }}
      - name: um-data-directory
        persistentVolumeClaim:
          claimName: {{ include "um-runtime.fullname" . }}