apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "microservices-runtime.fullname" . }}
  labels:
    {{- include "microservices-runtime.labels" . | nindent 4 }}
data:
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "application/application.properties" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "application/ediint-properties.cnf" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "licenses/msr-licenseKey.xml" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}
{{- $fileName := printf "%s/%s" (tpl .Values.environment . ) "licenses/terracotta-license.key" }}
  {{ $fileName | base}}: |-
{{ .Files.Get $fileName | indent 4 }}      