{{- if .Values.podConfig.autoScaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "microservices-runtime.fullname" . }}
  labels:
    {{- include "microservices-runtime.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Statefulset
    name: {{ include "microservices-runtime.fullname" . }}
  minReplicas: {{ .Values.podConfig.autoScaling.minReplicas }}
  maxReplicas: {{ .Values.podConfig.autoScaling.maxReplicas }}
  metrics:
    {{- if .Values.podConfig.autoScaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.podConfig.autoScaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.podConfig.autoScaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.podConfig.autoScaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}