{{- if .Values.jobForDCCAssets.enabled }} 
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "dcc-runtime.fullname" . }}
  {{- with .Values.jobForDCCAssets.podConfig.annotations }} 
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  backoffLimit: {{ .Values.jobForDCCAssets.backoffLimit }}
  completions: {{ .Values.jobForDCCAssets.completions }}
  template:
    metadata:
      {{- with .Values.jobForDCCAssets.podConfig.annotations }} 
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.jobForDCCAssets.podConfig.affinity }}   
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}      
      {{- with .Values.jobForDCCAssets.podConfig.tolerations }}                           
      tolerations:
        {{- toYaml . | nindent 8 }}    
      {{- end }} 
      securityContext:
        {{- toYaml .Values.jobForDCCAssets.podConfig.podSecurityContext | nindent 8 }} 
      serviceAccountName: {{ .Values.jobForDCCAssets.podConfig.serviceAccountName }}
      restartPolicy: {{ .Values.jobForDCCAssets.podConfig.restartPolicy }}
      containers:
      - name: {{ include "dcc-runtime.fullname" . }}-job-primary-container
        image: {{ .Values.jobForDCCAssets.podConfig.primaryContainer.image.repository }}:{{ .Values.jobForDCCAssets.podConfig.primaryContainer.image.tag }}
        env:
        - name: DB_IS_USER
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.jobForDCCAssets.podConfig.secretName }}
              key: DB_IS_USER
        - name: DB_IS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name:  {{ .Values.jobForDCCAssets.podConfig.secretName }}
              key: DB_IS_PASSWORD
        - name: DB_MWS_USER
          valueFrom:
            secretKeyRef: 
              name: {{ .Values.jobForDCCAssets.podConfig.secretName }}
              key: DB_MWS_USER
        - name: DB_MWS_PASSWORD
          valueFrom:
            secretKeyRef: 
              name:  {{ .Values.jobForDCCAssets.podConfig.secretName }}
              key: DB_MWS_PASSWORD
        - name: DB_TYPE
          valueFrom:
            configMapKeyRef: 
              name:  {{ include "dcc-runtime.fullname" . }}
              key: DB_TYPE        
        - name: DB_IS_URL
          valueFrom:
            configMapKeyRef: 
              name:  {{ include "dcc-runtime.fullname" . }}
              key: DB_IS_URL
        - name: DB_MWS_URL
          valueFrom:
            configMapKeyRef: 
              name:  {{ include "dcc-runtime.fullname" . }}
              key: DB_MWS_URL              
        - name: DB_TABLESPACE
          valueFrom:
            configMapKeyRef: 
              name:  {{ include "dcc-runtime.fullname" . }}
              key: DB_TABLESPACE       
        - name: DB_TABLESPACEINDEX
          valueFrom:
            configMapKeyRef: 
              name:  {{ include "dcc-runtime.fullname" . }}
              key: DB_TABLESPACEINDEX   
        command: 
        - /bin/bash
        - -c 
        - |
         /opt/softwareag/common/db/bin/dbConfigurator.sh -a create -pr MWS -v latest -d $(DB_TYPE) -l '$(DB_MWS_URL)' -u '$(DB_MWS_USER)' -p '$(DB_MWS_PASSWORD)' 
         /opt/softwareag/common/db/bin/dbConfigurator.sh -a create -pr IntegrationServer,TradingNetworks -c processengine,processaudit -v latest -d $(DB_TYPE) -l '$(DB_IS_URL)' -u '$(DB_IS_USER)' -p '$(DB_IS_PASSWORD)' 
{{- end }}