---
fullnameOverride: ""
nameOverride: ""
environment: dev

podConfig:    
  tolerations: 
    - key: "app"
      operator: "Equal"
      value: "b2b"
      effect: "NoSchedule" 
  # Options for node affinity for pod placement is required | preferred. Whether affinity is required or not is decided by setNodeAffinity parameter that can be set to true | false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In
            values:
            - "b2b" 
  #securityConext values
  podSecurityContext:
    fsGroup: 1724
    runAsUser: 1724
  serviceAccountName: b2b-sa
  replicas: 2
  podManagementPolicy: OrderedReady
  updateStrategy: RollingUpdate
  partition: 0
  appName: b2b
  # Secret to be used to pull the image from repository
  imagePullSecrets: regcred
  # Volume Claim Templates
  diskAccessMode: ReadWriteOnce
  storageClassName: local-path
  diskStorage: 2Gi
  primaryContainer:
    image: 
      repository: sagcr.azurecr.io/bigmemorymax-server
      tag: "4.4" 
      pullPolicy: IfNotPresent
    stripeCount: 1
    nodeCountPerStripe: 2
    restartable: false
    jsonLogging: false
    lifecycle: []
    dataStoreSize: "5G"
    offHeapSize: "2G"
    # Can be used for passing some jvm related options for terracotta servers.
    serverOpts: ""
    # Can be used for passing some jvm related options for tmc.
    tmcOpts: ""
    security: false
    selfSignedCerts: true
    # Create a secret manually in cluster which contains all the necessary certs, files etc. for all the servers 
    # as well as tmc as the same secret will be mounted to all the pods deployed via this helm chart.
    secretName:
    #Ports
    ports:
      - containerPort: 9510
        name: server
      - containerPort: 9530
        name: replication
      - containerPort: 9540
        name: management
    # Resources required for the apigateway to function. CPUs and Memory configurations.
    resources:
      limits:
        cpu: 1
        memory: "4G"
      requests:
        cpu: 1
        memory: "4G" 
    # Liveness probe to check whether container is active. Restart happens when liveness probe fails.
    livenessProbe:
      tcpSocket:
        port: 9530
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
      failureThreshold: 3
    # Readiness probe to check whether container is ready. Restart happens when readiness probe fails.
    readinessProbe:
      tcpSocket:
        port: 9530
      initialDelaySeconds: 30
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 5
      failureThreshold: 3
    startupProbe:
      tcpSocket:
        port: 9530
      initialDelaySeconds: 0
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 5
      failureThreshold: 100
    # Volume mount required for the application to function
    runtimePath: /opt/softwareag/run
    tcConfigPath: /opt/softwareag/config/tc-config.xml
    tcConfigFileName: tc-config.xml
    tcLicensePath: /opt/softwareag/config/license.key
    tcLicenseFileName: terracotta-license.key
#Service definition
service:
  type: ClusterIP
  serverPort: 9510
headlessPortDef:
  - port: 9510
    name: tcp-server     
  - port: 9530
    name: tcp-replication
  - port: 9540
    name: tcp-management
    targetPort: 9540  